-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 21:44:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas` DEFAULT CHARACTER SET utf8 ;
USE `ventas` ;

-- -----------------------------------------------------
-- Table `ventas`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`cliente` ;

CREATE TABLE IF NOT EXISTS `ventas`.`cliente` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fecha_registro` DATE NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


# procedures

DELIMITER &&
CREATE PROCEDURE SP_AGREGAR (IN nombre varchar(150), IN apellido varchar(150), IN email varchar(150), IN telefono varchar(20))
BEGIN
    INSERT INTO cliente (nombre, apellido, email, telefono, fecha_registro)
    VALUES (nombre, apellido, email,telefono, SYSDATE());
END &&
DELIMITER ;



DELIMITER &&
CREATE PROCEDURE SP_ELIMINAR (IN id int)
BEGIN
    DELETE FROM cliente WHERE codigo = id;
END &&
DELIMITER ;


DELIMITER &&
CREATE PROCEDURE SP_ACTUALIZAR(IN id int, IN nombre varchar(150), IN apellido varchar(150), IN email varchar(150),
                               IN telefono varchar(20))
BEGIN
    UPDATE cliente
    SET nombre=nombre,
        apellido=apellido,
        email=email,
        telefono=telefono
    WHERE codigo = id;
END &&
DELIMITER;
